name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    # Step 3: Build the Docker image
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/oslo-kommune-bystyrets-sekretariat/forks-gotenberg:8

    # Step 4: Push the Docker image to GitHub Packages
    - name: Push Docker image to GitHub Container Registry
      run: |
        docker push ghcr.io/${{ toLower(github.repository_owner) }}/forks-gotenberg:8
